name: nostradamus-platform

services:
  valkey-0:
    image: valkey/valkey:latest
    container_name: valkey-0
    command: >
      valkey-server
      --port 6379
      --cluster-enabled yes
      --cluster-config-file nodes.conf
      --cluster-node-timeout 5000
      --appendonly yes
      --cluster-announce-ip valkey-0
    ports:
      - "6379:6379"
    volumes:
      - valkey_data_0:/data
    networks:
      nostradamus:
        ipv4_address: 172.28.0.11
    healthcheck:
      test: ["CMD", "valkey-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 2

  valkey-1:
    image: valkey/valkey:latest
    container_name: valkey-1
    command: >
      valkey-server
      --port 6379
      --cluster-enabled yes
      --cluster-config-file nodes.conf
      --cluster-node-timeout 5000
      --appendonly yes
      --cluster-announce-ip valkey-1
    ports:
      - "6380:6379"
    volumes:
      - valkey_data_1:/data
    networks:
      nostradamus:
        ipv4_address: 172.28.0.12
    healthcheck:
      test: ["CMD", "valkey-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 2

  valkey-2:
    image: valkey/valkey:latest
    container_name: valkey-2
    command: >
      valkey-server
      --port 6379
      --cluster-enabled yes
      --cluster-config-file nodes.conf
      --cluster-node-timeout 5000
      --appendonly yes
      --cluster-announce-ip valkey-2
    ports:
      - "6381:6379"
    volumes:
      - valkey_data_2:/data
    networks:
      nostradamus:
        ipv4_address: 172.28.0.13
    healthcheck:
      test: ["CMD", "valkey-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 2

  valkey-init:
    image: valkey/valkey:latest
    container_name: valkey-init
    depends_on:
      valkey-0:
        condition: service_healthy
      valkey-1:
        condition: service_healthy
      valkey-2:
        condition: service_healthy
    entrypoint: ["/opt/scripts/init-valkey.sh"]
    volumes:
      - ./scripts/init-valkey.sh:/opt/scripts/init-valkey.sh:ro
    networks:
      - nostradamus

  scylla-0:
    container_name: scylla-0
    image: scylladb/scylla:latest
    command:
      - --seeds=scylla-0
      - --listen-address=scylla-0
      - --broadcast-address=scylla-0
      - --broadcast-rpc-address=scylla-0
      - --rpc-address=0.0.0.0
      - --api-address=0.0.0.0
      - --smp=1
      - --memory=2G
      - --overprovisioned=1
      - --reactor-backend=epoll
    ports:
      - "9042:9042"
    volumes:
      - scylla_data_0:/var/lib/scylla
    networks:
      - nostradamus
    healthcheck:
      test: ["CMD", "cqlsh", "-e", "SHOW HOST"]
      interval: 10s
      timeout: 5s
      retries: 3

  scylla-1:
    container_name: scylla-1
    image: scylladb/scylla:latest
    command:
      - --seeds=scylla-0
      - --listen-address=scylla-1
      - --broadcast-address=scylla-1
      - --rpc-address=0.0.0.0
      - --broadcast-rpc-address=scylla-1
      - --api-address=0.0.0.0
      - --smp=1
      - --memory=2G
      - --overprovisioned=1
      - --reactor-backend=epoll
    ports:
      - "9043:9042"
    volumes:
      - scylla_data_1:/var/lib/scylla
    networks:
      - nostradamus
    healthcheck:
      test: ["CMD", "cqlsh", "-e", "SHOW HOST"]
      interval: 10s
      timeout: 5s
      retries: 3

  scylla-2:
    container_name: scylla-2
    image: scylladb/scylla:latest
    command:
      - --seeds=scylla-0
      - --listen-address=scylla-2
      - --broadcast-address=scylla-2
      - --rpc-address=0.0.0.0
      - --broadcast-rpc-address=scylla-2
      - --api-address=0.0.0.0
      - --smp=1
      - --memory=2G
      - --overprovisioned=1
      - --reactor-backend=epoll
    ports:
      - "9044:9042"
    volumes:
      - scylla_data_2:/var/lib/scylla
    networks:
      - nostradamus
    healthcheck:
      test: ["CMD", "cqlsh", "-e", "SHOW HOST"]
      interval: 10s
      timeout: 5s
      retries: 3

  scylla-keyspace-init:
    container_name: scylla-keyspace-init
    image: scylladb/scylla:latest
    environment:
      - CQLSH_HOST=scylla-0
    entrypoint: ["cqlsh", "-f", "/opt/init_keyspaces.cql"]
    volumes:
      - ./init_keyspaces.cql:/opt/init_keyspaces.cql:ro
    networks:
      - nostradamus
    depends_on:
      scylla-0:
        condition: service_healthy
      scylla-1:
        condition: service_healthy
      scylla-2:
        condition: service_healthy

  migration:
    container_name: migration
    image: migrate/migrate
    command: >
      -path=/opt/migrations
      -database cassandra://scylla-0:9042/sensors_meta
      up
    volumes:
      - ./migrations:/opt/migrations:ro
    networks:
      - nostradamus
    depends_on:
      scylla-keyspace-init:
        condition: service_completed_successfully

  api:
    container_name: api
    image: api:latest
    build: .
    environment:
      - VALKEY_NODES=valkey-0:6379,valkey-1:6380,valkey-2:6381
      - SCYLLA_NODES=scylla-0:9042,scylla-1:9042,scylla-2:9042
      - ARROYO_URL=192.168.1.157
      - EMQX_URL=192.168.1.158:18083
      - EMQX_API_KEY=${EMQX_API_KEY}
      - EMQX_API_SECRET=${EMQX_API_SECRET}
    ports:
      - "8080:8080"
    networks:
      - nostradamus
    depends_on:
      migration:
        condition: service_completed_successfully
      valkey-init:
        condition: service_completed_successfully

networks:
  nostradamus:
    name: nostradamus-platform
    driver: bridge
    ipam:
      config:
        - subnet: 172.28.0.0/16

volumes:
  valkey_data_0:
    name: valkey-data-0
  valkey_data_1:
    name: valkey-data-1
  valkey_data_2:
    name: valkey-data-2
  scylla_data_0:
    name: scylla-data-0
  scylla_data_1:
    name: scylla-data-1
  scylla_data_2:
    name: scylla-data-2
